name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t local/example .
        echo -n "verifying images:"
        docker images
    - name: Download Istio
      run:
        curl -L https://istio.io/downloadIstio | sh -
    - name: install demo profile
      run:
        ./istio-1.22.0/bin/istioctl install --set profile=demo -y
    - name: enable istio-injection on default namespace
      run:
        kubectl label namespace default istio-injection=enabled
    - name: Deploy bookinfo app to minikube
      run:
        kubectl apply -f bookinfo.yaml
    - name: Create gateway
      run:
        kubectl apply -f bookinfo-gateway.yaml
    - name: Test service URLs
      run: |
        minikube service list     
