on:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'main.go'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master
        uses: actions/checkout@main
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build container image
        run: docker build -t registry.digitalocean.com/jimmysjoint/istio-lab:$(echo $GITHUB_SHA | head -c7) .
        
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
        
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/jimmysjoint/istio-lab:$(echo $GITHUB_SHA | head -c7)

      - name: Update deployment file
        run: TAG=$(echo $GITHUB_SHA | head -c7) && sed -i 's|istio-lab|registry.digitalocean.com/jimmysjoint/istio-lab:'${TAG}'|' $GITHUB_WORKSPACE/config/deployment.yaml

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 <cluster-name>

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yaml

      - name: Verify deployment
        run: kubectl rollout status deployment/gopher-hello-app
